### ISSUE TITLE
Console error when creating an auction and the auction doesn't persist after server restart

### ISSUE THREAD

**Issue by MadPanCake** [AuctionMaster/AuctionMaster#7]
Hello,

My server version: 1.19.4 (git-paper-550)
Auction Master: 4.7 - from this github

**What happens:**

Whenever I create an auction, a console error pop-ups:
```
[11:22:35 WARN]: java.net.MalformedURLException: no protocol:
[11:22:35 WARN]:        at java.base/java.net.URL.<init>(URL.java:674)
[11:22:35 WARN]:        at java.base/java.net.URL.<init>(URL.java:569)
[11:22:35 WARN]:        at java.base/java.net.URL.<init>(URL.java:516)
[11:22:35 WARN]:        at AuctionMaster.jar//me.intel.AuctionMaster.Utils.Utils.lambda$sendWebhook$1(Utils.java:48)
[11:22:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:22:35 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table Auctions has 11 columns but 10 values were supplied)
[11:22:35 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[11:22:35 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[11:22:35 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[11:22:35 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[11:22:35 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
[11:22:35 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[11:22:35 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[11:22:35 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[11:22:35 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[11:22:35 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[11:22:35 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
[11:22:35 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
[11:22:35 WARN]:        at AuctionMaster.jar//me.intel.AuctionMaster.database.SQLiteDatabase.lambda$insertAuction$10(SQLiteDatabase.java:399)
[11:22:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:22:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:22:35 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:22:35 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:22:35 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:22:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

The item displays in Auction Browser, I can edit or delete it and probably also buy (can't check as auction owner)
However, when I restart the server, the item is gone.

This issue also exists on a clean server installation (same paper and plugin version), with just these plugins:
![image](https://github.com/AuctionMaster/AuctionMaster/assets/34662922/7b2e325f-95d3-4178-b173-6f1f61dafa74)

**Comment by kotlinsyntax** [comment]
Fixed in commit 881d1361596a8da905ef874c3c0a795689c7abec
