### ISSUE TITLE
Bug edit price of bid

### ISSUE THREAD

**Issue by VentureStudios** [AuctionMaster/AuctionMaster#9]
Hi, when I try to change the auction price I get this error:

[10:10:10 WARN]: Player zPeppo_ just tried to change non-editable sign

**Comment by VentureCraftGit** [comment]
[10:17:57 ERROR]: Could not pass event InventoryClickEvent to AuctionMaster v4.8.0

java.lang.ExceptionInInitializerError: null

at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:550) ~[AuctionMaster-4.8.0.jar:?]

at me.intel.AuctionMaster.InputGUIs.StartingBidGUI.StartingBidGUI.anvilTrigger(StartingBidGUI.java:74) ~[AuctionMaster-4.8.0.jar:?]

at me.intel.AuctionMaster.Menus.CreateAuctionMainMenu$ClickListen.onClick(CreateAuctionMainMenu.java:450) ~[AuctionMaster-4.8.0.jar:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1111.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:git-Pufferfish-29]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3103) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1326) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1303) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1296) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1373) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1158) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[pufferfish-1.20.2.jar:git-Pufferfish-29]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: java.lang.ClassCastException: class net.wesjd.anvilgui.version.Wrapper1_20_R2 cannot be cast to class net.wesjd.anvilgui.version.VersionWrapper (net.wesjd.anvilgui.version.Wrapper1_20_R2 is in unnamed module of loader 'KTools-1.16+-2.2.2-SNAPSHOT.jar' @6a52f37f; net.wesjd.anvilgui.version.VersionWrapper is in unnamed module of loader 'AuctionMaster-4.8.0.jar' @1a4b09cd)

at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:30) ~[AuctionMaster-4.8.0.jar:?]

at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42) ~[AuctionMaster-4.8.0.jar:?]

... 27 more

**Comment by VentureCraftGit** [comment]
I tried putting:

use-anvil-instead-sign: true

use-chat-instead-sign: true

But it does not work.

**Comment by Teaftc** [comment]
I have the same error as you, have you solved it now?

**Comment by VentureStudios** [comment]
i have changed plugin...

**Comment by VentureStudios** [comment]
Bye
